gpu_idx: null  # CUDA device index
metric: container_cpu  # metric type
application_name: collector  # application name
sub_sample_rate: 1  # sub-sample rate
aggregation_type: max  # aggregation type
data_length_limit_in_minutes: 60  # data length limit in minutes
transformation_method: null  # transformation method: log, null
scale_method: null  # scaling method: min-max, null
look_back: 12  # look back window size
horizon: 2  # prediction horizon
model_name: LSTM  # model name: TCN, DeepAR, LSTM
trained_model_path: null  # path to a pre-trained model
num_epochs: 50  # number of epochs
batch_size: 4  # batch size
output_path: null  # output path
run_name: check_fastai  # optional run name
